# Generated by Django 4.0.4 on 2022-07-06 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chim_channel', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Videos',
        ),
    ]
